import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const upstreamThemePath = resolve(process.cwd(), "drcmda/poimandres-theme/src/theme.js");
const outputPath = resolve(process.cwd(), "src/generated-source-theme-assignments.ts");

/**
 * Parses the schema() template in theme.js and returns a mapping of
 * paletteKey → sorted list of VS Code token names that reference it.
 *
 * Only tokens whose value is a pure ${colors.X} reference (with optional
 * hex suffix like 40, b3, etc.) are included. Hardcoded hex literals are
 * ignored since they don't participate in palette mapping.
 */
function extractSourceAssignments(source: string): Record<string, string[]> {
	// Match "vsCodeToken": "${colors.paletteKey}" with optional alpha suffix
	const TOKEN_REFERENCE_REGEX = /"([^"]+)":\s*"\$\{colors\.([A-Za-z0-9]+)\}[^"]*"/g;

	const assignments: Record<string, string[]> = {};

	for (const match of source.matchAll(TOKEN_REFERENCE_REGEX)) {
		const vsCodeToken = match[1];
		const paletteKey = match[2];
		if (!assignments[paletteKey]) {
			assignments[paletteKey] = [];
		}
		if (!assignments[paletteKey].includes(vsCodeToken)) {
			assignments[paletteKey].push(vsCodeToken);
		}
	}

	// Sort keys and token lists for stable output
	return Object.fromEntries(
		Object.entries(assignments)
			.sort(([a], [b]) => a.localeCompare(b))
			.map(([key, tokens]) => [key, tokens.sort()]),
	);
}

const upstreamSource = readFileSync(upstreamThemePath, "utf8");
const assignments = extractSourceAssignments(upstreamSource);

const generated =
	`// Auto-generated by src/generate-source-token-assignments.ts\n` +
	`// Re-run with: pnpm generate:source-assignments\n` +
	`export const SOURCE_THEME_TOKEN_ASSIGNMENTS = ${JSON.stringify(assignments, null, "\t")} as const;\n`;

writeFileSync(outputPath, generated);
console.log(`wrote ${outputPath} (${Object.keys(assignments).length} palette keys)`);
